blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://github.com/md-shamim-ahmad/LeetCode-Problem-Solution/discussions
    about: Please ask and answer questions here.
