name: "Feature Request"
description: "Suggest an idea for this project"
title: "[Problem Name] <title>"
labels: ["enhancement","hacktoberfest-accepted"]
body:
  - type: textarea
    id: description
    attributes:
      label: Which problem do you want to solve?
      description: Provide a clear and concise explanation of the problem.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        For new implementations, please specify the name and problem statement for the leetcode problem.        
  - type: textarea
    id: needdetails
    attributes:
      label: "Input and Output details"
      description: "Write down all the input and output details description mentioned above."
    validations:
      required: true
  - type: textarea
    id: extrainfo
    attributes:
      label: "Additional Information"
      description: "Add any other information or screenshots about the request here."
    validations:
      required: false
