name: Other
description: Use this for any other issues. Do NOT create blank issues
title: "[OTHER]"
labels: ["awaiting triage"]

<!-- Thanks for filing an issue! Before submitting, please fill in the following information. -->

<!--Required Information-->

**This is a(n):**
<!-- choose one by changing [ ] to [x] -->
- [ ] Solution of new problem
- [ ] Update to an existing solution
- [ ] Error

**Details:**
<!-- Details of algorithm to be added/updated -->
